package sat.solver;

/**
 * A tool for determining the satisfiability of boolean expressions 
 * using the reduction rule database generated by sat.ruledb.RuleGenerator.
 * 
 * @author Ted Stockwell <emorning@yahoo.com>
 */
public class Solver {

}
