package sat.solver;

import java.io.FileInputStream;
import java.io.IOException;

import sat.Constant;
import sat.Formula;
import sat.Implication;
import sat.PropositionalSystem;
import sat.Variable;
import sat.ruledb.RuleDatabase;
import sat.utils.ArgUtils;

/**
 * A tool for determining the satisfiability of boolean expressions 
 * using the reduction rule database generated by sat.ruledb.RuleGenerator.
 * 
 * @author Ted Stockwell <emorning@yahoo.com>
 */
public class Solver {
	
	public static void main(String[] args) throws IOException {
		PropositionalSystem system= new PropositionalSystem();
		String file= ArgUtils.getString(args, "file", true);
		CNFFile cnf= CNFFile.read(system, new FileInputStream(file));
		
		Solver solver= new Solver(system, new RuleDatabase());
		Formula reducedForm= solver.reduce(cnf.getFormula());
		
		// produce output according to rules here:
		// 	http://www.satcompetition.org/2004/format-solvers2004.html
		int status;
		if (Constant.FALSE.equals(reducedForm)) {
			System.out.println("s UNSATISFIABLE");
			status= 20;
		}
		else {
			System.out.println("s SATISFIABLE");
			printSatisfyingValuation(reducedForm);
			status= 10;
		}
		System.exit(status);
	}
	
	private PropositionalSystem _system;
	private RuleDatabase _ruleDatabase; 
	public Solver(PropositionalSystem system, RuleDatabase ruleDatabase) { 
		_system= system;
		_ruleDatabase= ruleDatabase;
	}
	
	

	private static void printSatisfyingValuation(Formula reducedForm) {
		// TODO Auto-generated method stub
		
	}

	public Formula reduce(Formula formula) {
		if (formula instanceof Negation) {
			return
		}
		if (formula instanceof Implication) {
			
		}
		return formula; // the given formula is a variable or constant
	}
	
	/**
	 * Only applies rules to the given formula, not subformulas
	 * @returns the reduced rule if a rule applied, else the given rule.
	 */
	private Formula applyRules(Formula formula) {
		
	}
}
