package sat.solver;

import java.io.FileInputStream;
import java.io.IOException;

import sat.Constant;
import sat.Formula;
import sat.PropositionalSystem;
import sat.utils.ArgUtils;

/**
 * A tool for determining the satisfiability of boolean expressions 
 * using the reduction rule database generated by sat.ruledb.RuleGenerator.
 * 
 * @author Ted Stockwell <emorning@yahoo.com>
 */
public class Solver {
	
	public static void main(String[] args) throws IOException {
		PropositionalSystem system= new PropositionalSystem();
		String file= ArgUtils.getString(args, "file", true);
		CNFFile cnf= CNFFile.read(system, new FileInputStream(file));
		Formula reducedForm= getMaximallyReducedForm(cnf.getFormula());
		
		// produce output according to rules here:
		// 	http://www.satcompetition.org/2004/format-solvers2004.html
		int status;
		if (Constant.FALSE.equals(reducedForm)) {
			System.out.println("s UNSATISFIABLE");
			status= 20;
		}
		else {
			System.out.println("s SATISFIABLE");
			printSatisfyingValuation(reducedForm);
			status= 10;
		}
		System.exit(status);
	}

	private static void printSatisfyingValuation(Formula reducedForm) {
		// TODO Auto-generated method stub
		
	}

	private static Formula getMaximallyReducedForm(Object formula) {
		// TODO Auto-generated method stub
		return null;
	}
}
