package com.googlecode.meteorframework.core.impl;

/**
 * A marker interface that identify Meteor objects were generated by Cglib.
 * 
 * In order to be able to identify cglib generated objects AND to access 
 * thier underlying ObjectImpl objects we add this interface to all cglib 
 * generated objects.
 * @author Ted Stockwell
 *
 */
public interface MeteorProxy {
	
	public ObjectImpl getObjectImpl();

}
